Document: artoolkitplus
Title: Debian artoolkitplus Manual
Author: <insert document author here>
Abstract: This manual describes what artoolkitplus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/artoolkitplus/artoolkitplus.sgml.gz

Format: postscript
Files: /usr/share/doc/artoolkitplus/artoolkitplus.ps.gz

Format: text
Files: /usr/share/doc/artoolkitplus/artoolkitplus.text.gz

Format: HTML
Index: /usr/share/doc/artoolkitplus/html/index.html
Files: /usr/share/doc/artoolkitplus/html/*.html

  
